name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-13, macos-12, macos-14, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Test
        run: make test
