name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-15, macos-14, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SDL2
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libsdl2-dev
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install sdl2
          fi
      - name: Build
        run: make build
      - name: Test
        run: make test
